export function buildReport(items = []) {

  const normalizedItems = items.map((item) => {

    const product = item?.product || item;

    return {
      product,
      quantity: Number(item?.quantity || 1)
    };

  });

  const totalUnits =
    normalizedItems.reduce(
      (sum, item) =>
        sum + item.quantity,
      0
    );

  const totalAmount =
    normalizedItems.reduce(
      (sum, item) => {

        const price = Number(
          item.product?.salePrice ??
          item.product?.mrp ??
          0
        );

        return sum + (price * item.quantity);

      },
      0
    );

  return {
    id: `report-${Date.now()}`,
    items: normalizedItems,
    totalUnits,
    totalAmount,
    createdAt: new Date().toISOString()
  };
}


export function reportToText(report) {

  if (!report) {
    return "GHARLIST Shopping Report";
  }

  const lines = [
    "GHARLIST SHOPPING REPORT",
    "=========================",
    "",
    `Date: ${new Date(
      report.createdAt
    ).toLocaleString("en-IN")}`,
    ""
  ];

  const items =
    report.items || [];

  items.forEach((item, index) => {

    const product =
      item.product || item;

    const quantity =
      Number(item.quantity || 1);

    const price =
      Number(
        product.salePrice ??
        product.mrp ??
        0
      );

    const total =
      price * quantity;

    lines.push(
      `${index + 1}. ${product.name}`
    );

    if (product.brand) {
      lines.push(
        `   Brand: ${product.brand}`
      );
    }

    if (product.quantity) {
      lines.push(
        `   Pack: ${product.quantity}`
      );
    }

    lines.push(
      `   Qty: ${quantity}`
    );

    lines.push(
      `   Price: ₹${price.toLocaleString("en-IN")}`
    );

    lines.push(
      `   Total: ₹${total.toLocaleString("en-IN")}`
    );

    lines.push("");
  });

  lines.push(
    "-------------------------"
  );

  lines.push(
    `Total Units: ${report.totalUnits || 0}`
  );

  lines.push(
    `Total Amount: ₹${Number(
      report.totalAmount || 0
    ).toLocaleString("en-IN")}`
  );

  lines.push("");
  lines.push("Generated by GHARLIST");

  return lines.join("\n");
}
