function normalizeQuantity(value) {
  const number = Number(value);
  return Number.isFinite(number) && number > 0
    ? Math.floor(number)
    : 1;
}

function normalizeProduct(product) {
  return product || {};
}

export function normalizeReportItems(items = []) {
  if (!Array.isArray(items)) {
    return [];
  }

  return items
    .map((item) => {
      const product = normalizeProduct(
        item?.product || item
      );

      const quantity = normalizeQuantity(
        item?.quantity ??
        item?.qty ??
        1
      );

      return {
        product,
        quantity
      };
    })
    .filter((item) => item.product?.id || item.product?.name);
}

export function calculateReportTotals(items = []) {
  const normalizedItems =
    normalizeReportItems(items);

  const totalItems =
    normalizedItems.length;

  const totalUnits =
    normalizedItems.reduce(
      (sum, item) =>
        sum + Number(item.quantity || 1),
      0
    );

  const totalAmount =
    normalizedItems.reduce(
      (sum, item) => {
        const price = Number(
          item.product?.salePrice ??
          item.product?.mrp ??
          0
        );

        return sum +
          (Number.isFinite(price)
            ? price
            : 0) *
          Number(item.quantity || 1);
      },
      0
    );

  return {
    totalItems,
    totalUnits,
    totalAmount
  };
}

export function buildReport(items = []) {
  const normalizedItems =
    normalizeReportItems(items);

  const totals =
    calculateReportTotals(normalizedItems);

  return {
    id: `report-${Date.now()}`,
    items: normalizedItems,
    ...totals,
    createdAt: new Date().toISOString()
  };
}

/*
  Important:
  Always recalculate totals from the actual
  item array. This repairs old reports that
  accidentally stored 0 totals.
*/
export function normalizeReport(report) {
  if (!report) {
    return null;
  }

  const items =
    normalizeReportItems(
      report.items || []
    );

  const totals =
    calculateReportTotals(items);

  return {
    ...report,
    items,
    ...totals,
    createdAt:
      report.createdAt ||
      new Date().toISOString()
  };
}

export function reportToText(report) {
  const normalized =
    normalizeReport(report);

  if (!normalized) {
    return "GHARLIST SHOPPING REPORT";
  }

  const lines = [
    "🛒 GHARLIST SHOPPING REPORT",
    "━━━━━━━━━━━━━━━━━━━━",
    "",
    `📅 ${new Date(
      normalized.createdAt
    ).toLocaleString("en-IN")}`,
    ""
  ];

  normalized.items.forEach(
    (item, index) => {
      const product = item.product || {};
      const quantity =
        Number(item.quantity || 1);

      const price =
        Number(
          product.salePrice ??
          product.mrp ??
          0
        );

      const lineTotal =
        price * quantity;

      lines.push(
        `${index + 1}. ${product.name || "Product"}`
      );

      if (product.brand) {
        lines.push(
          `   🏷️ ${product.brand}`
        );
      }

      if (product.quantity) {
        lines.push(
          `   📦 ${product.quantity}`
        );
      }

      lines.push(
        `   🔢 Qty: ${quantity}`
      );

      lines.push(
        `   💰 ₹${price.toLocaleString("en-IN")}`
      );

      lines.push(
        `   Total: ₹${lineTotal.toLocaleString("en-IN")}`
      );

      lines.push("");
    }
  );

  lines.push(
    "━━━━━━━━━━━━━━━━━━━━"
  );

  lines.push(
    `🛍️ Total Items: ${normalized.totalItems}`
  );

  lines.push(
    `📦 Total Quantity: ${normalized.totalUnits}`
  );

  lines.push(
    `💰 Total Amount: ₹${Number(
      normalized.totalAmount
    ).toLocaleString("en-IN")}`
  );

  lines.push(
    "━━━━━━━━━━━━━━━━━━━━"
  );

  lines.push("");
  lines.push(
    "Generated by GHARLIST"
  );
  lines.push(
    "Smart Family Shopping Assistant"
  );

  return lines.join("\n");
}