import { reportToText } from "./reportService.js";

export async function copyReport(report) {

  const text = reportToText(report);

  try {

    await navigator.clipboard.writeText(text);

    alert("Shopping report copied!");

    return true;

  } catch (error) {

    console.error(
      "Clipboard failed:",
      error
    );

    alert(
      "Copy failed. Please try again."
    );

    return false;
  }
}


export async function shareReport(report) {

  const text =
    reportToText(report);

  if (
    navigator.share
  ) {

    try {

      await navigator.share({
        title: "GHARLIST Shopping Report",
        text
      });

      return true;

    } catch (error) {

      if (
        error?.name === "AbortError"
      ) {
        return false;
      }

      console.error(
        "Share failed:",
        error
      );
    }
  }

  return copyReport(report);
}


export function shareWhatsApp(report) {

  const text =
    encodeURIComponent(
      reportToText(report)
    );

  const url =
    `https://wa.me/?text=${text}`;

  window.open(
    url,
    "_blank",
    "noopener,noreferrer"
  );
}


export function shareEmail(report) {

  const subject =
    encodeURIComponent(
      "GHARLIST Shopping Report"
    );

  const body =
    encodeURIComponent(
      reportToText(report)
    );

  window.location.href =
    `mailto:?subject=${subject}&body=${body}`;
}


export function printReport(report) {

  const text =
    reportToText(report);

  const printWindow =
    window.open(
      "",
      "_blank",
      "width=800,height=900"
    );

  if (!printWindow) {

    alert(
      "Please allow pop-ups to print the report."
    );

    return;
  }

  const escapedText =
    text
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;");

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>GHARLIST Shopping Report</title>

        <style>
          body {
            font-family:
              Arial,
              Helvetica,
              sans-serif;
            padding: 40px;
            color: #173e2e;
          }

          h1 {
            color: #07883f;
            margin-bottom: 25px;
          }

          pre {
            white-space: pre-wrap;
            line-height: 1.7;
            font-size: 14px;
          }

          .footer {
            margin-top: 35px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            color: #777;
            font-size: 12px;
          }

          @media print {
            body {
              padding: 20px;
            }
          }
        </style>
      </head>

      <body>

        <h1>GHARLIST</h1>

        <pre>${escapedText}</pre>

        <div class="footer">
          Generated by GHARLIST Smart Family Shopping Assistant
        </div>

        <script>
          window.onload = function () {
            window.print();
          };
        <\/script>

      </body>
    </html>
  `);

  printWindow.document.close();
}
